# Site settings
title: Andhika H. Santoso Portofolio
email: andhika.haeruman@gmx.com
description: > # this means to ignore newlines until "baseurl:"
  Andhika Ganteng Sekali, Andhika Ganteng Sekali.
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "vanestorz.github.io" # the base hostname & protocol for your site
twitter_username: dika_haeruman
github_username:  vanestorz

# Build settings
markdown: kramdown
